### ISSUE TITLE
Support system-internal-tls in net-istio

### ISSUE THREAD

**Issue by ReToCode** [knative-extensions/net-istio#1063]
Larger description in the [Feature Track document](https://docs.google.com/document/d/1XE7UzgQlVVtAb7ULSqOyKCaIHtm8zMF35ainp1JmwyY/edit?resourcekey=0-e1MXRxQaalq-EHW46ZCCWg#heading=h.n8a530nnrb)
Parent-issue: https://github.com/knative/serving/issues/11906

**Summary**
net-istio should support calling activator / backends with a known CA key and subject name.

/kind feature-request

**Comment by nak3** [comment]
If all net-* plugins are going to support the TLS encryption for the path `Ingress -> backend`, would it be better to add: 
* conformance test in networking repo
* and KIngress contract which means adding API for KIngress ?

**Comment by nak3** [comment]
(This may be off topic but) for the Kingress API addition, if we add the "SanName" field it would also help to solve https://github.com/knative/serving/issues/12797 by using the SAN for each ingress like:

(based on [Feature Track document](https://docs.google.com/document/d/1XE7UzgQlVVtAb7ULSqOyKCaIHtm8zMF35ainp1JmwyY/edit?resourcekey=0-e1MXRxQaalq-EHW46ZCCWg#heading=h.n8a530nnrb))
```go
type InternalTLS struct {
        // SecretName is the name of the secret used to SSL traffic against upstream(backend).
        // The secret should store the CA (root) cert to use SSL traffic.
        SecretName string `json:"secretName,omitempty"`
       
	// SanName is the name of SAN which s verified if at least one of SAN is matched.
        // The field is array to store two SANs such as activator and queue-proxy.
        SanName []string `json:"secretName,omitempty"`
}
```

(I know we should use SNI but I think SNI solution is not possible...)
