### ISSUE TITLE
Add default TLS cert

### ISSUE THREAD

**Issue by BobyMCbobs** [knative-extensions/net-istio#1130]
use an existing secret for TLS termination.

similar to https://github.com/knative-sandbox/net-contour/pull/193

/assign

**Comment by nak3** [comment]
Hi @BobyMCbobs

net-istio has two TLS setup
a) [Manually adding a TLS certificate](https://knative.dev/docs/serving/using-a-tls-cert/#manually-adding-a-tls-certificate)
b) [Enabling auto-TLS certs](https://knative.dev/docs/serving/using-auto-tls/)

I assume that you want to add the default TLS cert for b) but then I guess it is a little bit difficult for net-istio.

Unlike Contour, Istio's Gateway does not support cross namespace secret[1][2]. Thereforce, we need to deploy secrets in every single namespace where net-istio generated the Gateway.

Contour can deploy the default secret in "some-admin-namespace", though.

Sorry if you have any other good solution but I just leave my comment here.

[1] https://github.com/istio/istio/issues/14598#issuecomment-1226083889
[2] https://istio.io/latest/docs/reference/config/networking/gateway/#ServerTLSSettings (Only `credentialName` is available)

**Comment by BobyMCbobs** [comment]
> Hi @BobyMCbobs
> 
> net-istio has two TLS setup a) [Manually adding a TLS certificate](https://knative.dev/docs/serving/using-a-tls-cert/#manually-adding-a-tls-certificate) b) [Enabling auto-TLS certs](https://knative.dev/docs/serving/using-auto-tls/)
> 
> I assume that you want to add the default TLS cert for b) but then I guess it is a little bit difficult for net-istio.

@nak3, thank you for your reply.
Yeah this is correct.
Ideally make it so that it uses a given TLS cert by default for a hostname wildcard and for anything else it uses net-certmanager.
I think I may need to write something custom for that functionality though.
Perhaps even a MutatingWebhookConfiguration could do it 🤔 

> Unlike Contour, Istio's Gateway does not support cross namespace secret[1][2]. Thereforce, we need to deploy secrets in every single namespace where net-istio generated the Gateway.
> 
> Contour can deploy the default secret in "some-admin-namespace", though.
> 
> Sorry if you have any other good solution but I just leave my comment here.
> 
> [1] [istio/istio#14598 (comment)](https://github.com/istio/istio/issues/14598#issuecomment-1226083889) [2] https://istio.io/latest/docs/reference/config/networking/gateway/#ServerTLSSettings (Only `credentialName` is available)
