### ISSUE TITLE
Bump Istio to v1.19

### ISSUE THREAD

**Issue by dprotaso** [knative-extensions/net-istio#1168]
New release is out https://github.com/istio/istio/releases

**Comment by ReToCode** [comment]
Same here

```text
# v1.19.0
go: istio.io/client-go@v1.19.0 requires k8s.io/apimachinery@v0.28.0, not k8s.io/apimachinery@v0.26.9
# v1.18.0
go: istio.io/client-go@v1.18.0 requires k8s.io/apimachinery@v0.27.0, not k8s.io/apimachinery@v0.26.9
```

So we can probably bump the manifests to test with 1.19, but client libs have to stay on 1.17.

**Comment by ReToCode** [comment]
New issue to just bump the manifests https://github.com/knative-extensions/net-istio/issues/1177. We'll keep this one open until we are on a higher k8s version.
