### ISSUE TITLE
New configuration format

### ISSUE THREAD

**Issue by pastequo** [knative-extensions/net-istio#1247]
This Issue comes from this design document: https://docs.google.com/document/d/12X1-9nhjAhpf-Wlt3RbdoMbvx31zFBva/edit#heading=h.gjdgxs

The proposal is to make the configuration more flexible, more extensible. This issue focus only on the new configuration format, without any filtering capabilities (that will come in another issue)

See the design document for more information

**Comment by nguyenthai0107** [comment]
Hello @pastequo .
Is there a way to implement with Nginx Ingress ?.
Im believe that a lot of company which was built and using technology and system base on Nginx Ingress ( without supported network layer such as Contour, Kourier, Istio). It will more options, more flexible if this was implemented in configmap.
Thank you.

**Comment by dprotaso** [comment]
@nguyenthai0107 nginx support would come through our use of the Gateway API - we have a plugin here but we haven't done any testing with nginx.

https://github.com/knative-extensions/net-gateway-api

Curious do you require the need to select different gateways?
