### ISSUE TITLE
Allow `STRICT` mode in the knative-serving namespace

### ISSUE THREAD

**Issue by braunsonm** [knative-extensions/net-istio#1258]
Right now the official documentation recommends setting `PERMISSIVE` mode on the `knative-serving` namespace. However it doesn't offer any explanation as to why.

When strict mode is enabled I notice that the autoscaler no longer seems to scale my instances up. However this is required to build a full chain of trust from the gateway -> activator -> workload.

Is there plans to support strict mode on the serving namespace in the future?

**Comment by dprotaso** [comment]
> Right now the official documentation recommends setting PERMISSIVE mode on the knative-serving namespace. 

Yeah that's surprising. The only valid reason to have that (I think) is incase you have Knative Services in a namespaces that doesn't have mTLS/sidecars enabled.

Funny enough we don't apply such a PeerAuth in our testing - we just have PeerAuth to allow the k8s api to invoke the webhooks.


> When strict mode is enabled I notice that the autoscaler no longer seems to scale my instances up. 

What's the default mode if it's not set - isnt' it `STRICT`?

**Comment by braunsonm** [comment]
> Funny enough we don't apply such a PeerAuth in our testing - we just have PeerAuth to allow the k8s api to invoke the webhooks.

This is likely because your mesh default is `PERMISSIVE`. For me the activator and autoscaler definitely can not communicate anymore if STRICT is enabled. Injection is enabled in all 3 namespaces (gateway, knative-serving, and the workload namespace)

> What's the default mode if it's not set - isnt' it STRICT?

It depends on your mesh config - by default it is `PERMISSIVE`.

**Comment by braunsonm** [comment]
Okay interestingly enough, after adjusting the `PeerAuthentication` mode I just needed to kick all the autoscalers. They came back up fine and can scale with `STRICT` mode.

So seems like when changing the mode the websocket connection breaks and can't reconcile itself.

**Comment by dprotaso** [comment]
> For me the autoscaler definitely can not communicate properly anymore if STRICT is enabled.

That's odd - because they should have sidecars enabled

**Comment by ReToCode** [comment]
We use STRICT in downstream, works as expected. Make sure you have istio sidecars injected in Activator and in Autoscaler pod to make everything work.
