### ISSUE TITLE
Add trusting a CA bundle to net-istio

### ISSUE THREAD

**Issue by ReToCode** [knative-extensions/net-istio#1328]
We need to add
https://github.com/knative/serving/issues/14609 for net-istio as well.

Related to https://github.com/knative/serving/issues/15276

**Comment by ReToCode** [comment]
After some discussions it seems that this is unnecessary. Trust-bundles are only relevant for `system-internal-tls`, which makes not a lot of sense for net-istio in the first place. Istio has this built in using the istio-proxies while forming a mesh. So to summarize:

- net-istio supports `cluster-local-domain-tls` which makes it capable of an ingress gateway with TLS mode: simple
- net-istio supports `external-domain-tls` (already available for a long time)
- net-istio will not support `system-internal-tls` as users can [just enable mesh integration](https://knative.dev/docs/install/installing-istio/#forming-a-service-mesh) to have connections between Ingress-Gateway <> Activator <> and Queue Proxies encrypted

**Comment by dprotaso** [comment]
> net-istio will not support system-internal-tls as users can [just enable mesh integration](https://knative.dev/docs/install/installing-istio/#forming-a-service-mesh) to have connections between Ingress-Gateway <> Activator <> and Queue Proxies encrypted

Should we rollback the feature added in https://github.com/knative-extensions/net-istio/pull/1085 ?

**Comment by ReToCode** [comment]
> Should we rollback the feature added in https://github.com/knative-extensions/net-istio/pull/1085 ?

Yeah I think that makes sense. I'll do a PR for that.
